# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mao/MEGA/phd-cloud/projects/LAGO/lagodetector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mao/MEGA/phd-cloud/projects/LAGO/lagodetector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mao/Documents/laboral/software/CDAS/ape/cmake/3.7.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mao/MEGA/phd-cloud/projects/LAGO/lagodetector/CMakeFiles /home/mao/MEGA/phd-cloud/projects/LAGO/lagodetector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mao/MEGA/phd-cloud/projects/LAGO/lagodetector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lago

# Build rule for target.
lago: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lago
.PHONY : lago

# fast build rule for target.
lago/fast:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/build
.PHONY : lago/fast

lago.o: lago.cc.o

.PHONY : lago.o

# target to build an object file
lago.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/lago.cc.o
.PHONY : lago.cc.o

lago.i: lago.cc.i

.PHONY : lago.i

# target to preprocess a source file
lago.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/lago.cc.i
.PHONY : lago.cc.i

lago.s: lago.cc.s

.PHONY : lago.s

# target to generate assembly for a file
lago.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/lago.cc.s
.PHONY : lago.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o

.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i

.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s

.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/CerValHistograms.o: src/CerValHistograms.cc.o

.PHONY : src/CerValHistograms.o

# target to build an object file
src/CerValHistograms.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerValHistograms.cc.o
.PHONY : src/CerValHistograms.cc.o

src/CerValHistograms.i: src/CerValHistograms.cc.i

.PHONY : src/CerValHistograms.i

# target to preprocess a source file
src/CerValHistograms.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerValHistograms.cc.i
.PHONY : src/CerValHistograms.cc.i

src/CerValHistograms.s: src/CerValHistograms.cc.s

.PHONY : src/CerValHistograms.s

# target to generate assembly for a file
src/CerValHistograms.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerValHistograms.cc.s
.PHONY : src/CerValHistograms.cc.s

src/CerenkovValidation.o: src/CerenkovValidation.cc.o

.PHONY : src/CerenkovValidation.o

# target to build an object file
src/CerenkovValidation.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerenkovValidation.cc.o
.PHONY : src/CerenkovValidation.cc.o

src/CerenkovValidation.i: src/CerenkovValidation.cc.i

.PHONY : src/CerenkovValidation.i

# target to preprocess a source file
src/CerenkovValidation.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerenkovValidation.cc.i
.PHONY : src/CerenkovValidation.cc.i

src/CerenkovValidation.s: src/CerenkovValidation.cc.s

.PHONY : src/CerenkovValidation.s

# target to generate assembly for a file
src/CerenkovValidation.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/CerenkovValidation.cc.s
.PHONY : src/CerenkovValidation.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/ExtraPhysics.o: src/ExtraPhysics.cc.o

.PHONY : src/ExtraPhysics.o

# target to build an object file
src/ExtraPhysics.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ExtraPhysics.cc.o
.PHONY : src/ExtraPhysics.cc.o

src/ExtraPhysics.i: src/ExtraPhysics.cc.i

.PHONY : src/ExtraPhysics.i

# target to preprocess a source file
src/ExtraPhysics.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ExtraPhysics.cc.i
.PHONY : src/ExtraPhysics.cc.i

src/ExtraPhysics.s: src/ExtraPhysics.cc.s

.PHONY : src/ExtraPhysics.s

# target to generate assembly for a file
src/ExtraPhysics.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/ExtraPhysics.cc.s
.PHONY : src/ExtraPhysics.cc.s

src/OpticalPhysics.o: src/OpticalPhysics.cc.o

.PHONY : src/OpticalPhysics.o

# target to build an object file
src/OpticalPhysics.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/OpticalPhysics.cc.o
.PHONY : src/OpticalPhysics.cc.o

src/OpticalPhysics.i: src/OpticalPhysics.cc.i

.PHONY : src/OpticalPhysics.i

# target to preprocess a source file
src/OpticalPhysics.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/OpticalPhysics.cc.i
.PHONY : src/OpticalPhysics.cc.i

src/OpticalPhysics.s: src/OpticalPhysics.cc.s

.PHONY : src/OpticalPhysics.s

# target to generate assembly for a file
src/OpticalPhysics.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/OpticalPhysics.cc.s
.PHONY : src/OpticalPhysics.cc.s

src/PMTHit.o: src/PMTHit.cc.o

.PHONY : src/PMTHit.o

# target to build an object file
src/PMTHit.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTHit.cc.o
.PHONY : src/PMTHit.cc.o

src/PMTHit.i: src/PMTHit.cc.i

.PHONY : src/PMTHit.i

# target to preprocess a source file
src/PMTHit.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTHit.cc.i
.PHONY : src/PMTHit.cc.i

src/PMTHit.s: src/PMTHit.cc.s

.PHONY : src/PMTHit.s

# target to generate assembly for a file
src/PMTHit.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTHit.cc.s
.PHONY : src/PMTHit.cc.s

src/PMTSD.o: src/PMTSD.cc.o

.PHONY : src/PMTSD.o

# target to build an object file
src/PMTSD.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTSD.cc.o
.PHONY : src/PMTSD.cc.o

src/PMTSD.i: src/PMTSD.cc.i

.PHONY : src/PMTSD.i

# target to preprocess a source file
src/PMTSD.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTSD.cc.i
.PHONY : src/PMTSD.cc.i

src/PMTSD.s: src/PMTSD.cc.s

.PHONY : src/PMTSD.s

# target to generate assembly for a file
src/PMTSD.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PMTSD.cc.s
.PHONY : src/PMTSD.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PhysicsListMessenger.o: src/PhysicsListMessenger.cc.o

.PHONY : src/PhysicsListMessenger.o

# target to build an object file
src/PhysicsListMessenger.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsListMessenger.cc.o
.PHONY : src/PhysicsListMessenger.cc.o

src/PhysicsListMessenger.i: src/PhysicsListMessenger.cc.i

.PHONY : src/PhysicsListMessenger.i

# target to preprocess a source file
src/PhysicsListMessenger.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsListMessenger.cc.i
.PHONY : src/PhysicsListMessenger.cc.i

src/PhysicsListMessenger.s: src/PhysicsListMessenger.cc.s

.PHONY : src/PhysicsListMessenger.s

# target to generate assembly for a file
src/PhysicsListMessenger.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PhysicsListMessenger.cc.s
.PHONY : src/PhysicsListMessenger.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/PrimaryGeneratorMessenger.o: src/PrimaryGeneratorMessenger.cc.o

.PHONY : src/PrimaryGeneratorMessenger.o

# target to build an object file
src/PrimaryGeneratorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorMessenger.cc.o
.PHONY : src/PrimaryGeneratorMessenger.cc.o

src/PrimaryGeneratorMessenger.i: src/PrimaryGeneratorMessenger.cc.i

.PHONY : src/PrimaryGeneratorMessenger.i

# target to preprocess a source file
src/PrimaryGeneratorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorMessenger.cc.i
.PHONY : src/PrimaryGeneratorMessenger.cc.i

src/PrimaryGeneratorMessenger.s: src/PrimaryGeneratorMessenger.cc.s

.PHONY : src/PrimaryGeneratorMessenger.s

# target to generate assembly for a file
src/PrimaryGeneratorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimaryGeneratorMessenger.cc.s
.PHONY : src/PrimaryGeneratorMessenger.cc.s

src/PrimarySpectrum.o: src/PrimarySpectrum.cc.o

.PHONY : src/PrimarySpectrum.o

# target to build an object file
src/PrimarySpectrum.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimarySpectrum.cc.o
.PHONY : src/PrimarySpectrum.cc.o

src/PrimarySpectrum.i: src/PrimarySpectrum.cc.i

.PHONY : src/PrimarySpectrum.i

# target to preprocess a source file
src/PrimarySpectrum.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimarySpectrum.cc.i
.PHONY : src/PrimarySpectrum.cc.i

src/PrimarySpectrum.s: src/PrimarySpectrum.cc.s

.PHONY : src/PrimarySpectrum.s

# target to generate assembly for a file
src/PrimarySpectrum.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/PrimarySpectrum.cc.s
.PHONY : src/PrimarySpectrum.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/StepMax.o: src/StepMax.cc.o

.PHONY : src/StepMax.o

# target to build an object file
src/StepMax.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/StepMax.cc.o
.PHONY : src/StepMax.cc.o

src/StepMax.i: src/StepMax.cc.i

.PHONY : src/StepMax.i

# target to preprocess a source file
src/StepMax.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/StepMax.cc.i
.PHONY : src/StepMax.cc.i

src/StepMax.s: src/StepMax.cc.s

.PHONY : src/StepMax.s

# target to generate assembly for a file
src/StepMax.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/StepMax.cc.s
.PHONY : src/StepMax.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/SteppingVerbose.o: src/SteppingVerbose.cc.o

.PHONY : src/SteppingVerbose.o

# target to build an object file
src/SteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingVerbose.cc.o
.PHONY : src/SteppingVerbose.cc.o

src/SteppingVerbose.i: src/SteppingVerbose.cc.i

.PHONY : src/SteppingVerbose.i

# target to preprocess a source file
src/SteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingVerbose.cc.i
.PHONY : src/SteppingVerbose.cc.i

src/SteppingVerbose.s: src/SteppingVerbose.cc.s

.PHONY : src/SteppingVerbose.s

# target to generate assembly for a file
src/SteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/SteppingVerbose.cc.s
.PHONY : src/SteppingVerbose.cc.s

src/histosRun.o: src/histosRun.cc.o

.PHONY : src/histosRun.o

# target to build an object file
src/histosRun.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/histosRun.cc.o
.PHONY : src/histosRun.cc.o

src/histosRun.i: src/histosRun.cc.i

.PHONY : src/histosRun.i

# target to preprocess a source file
src/histosRun.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/histosRun.cc.i
.PHONY : src/histosRun.cc.i

src/histosRun.s: src/histosRun.cc.s

.PHONY : src/histosRun.s

# target to generate assembly for a file
src/histosRun.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/histosRun.cc.s
.PHONY : src/histosRun.cc.s

src/water.o: src/water.cc.o

.PHONY : src/water.o

# target to build an object file
src/water.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water.cc.o
.PHONY : src/water.cc.o

src/water.i: src/water.cc.i

.PHONY : src/water.i

# target to preprocess a source file
src/water.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water.cc.i
.PHONY : src/water.cc.i

src/water.s: src/water.cc.s

.PHONY : src/water.s

# target to generate assembly for a file
src/water.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water.cc.s
.PHONY : src/water.cc.s

src/water2.o: src/water2.cc.o

.PHONY : src/water2.o

# target to build an object file
src/water2.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water2.cc.o
.PHONY : src/water2.cc.o

src/water2.i: src/water2.cc.i

.PHONY : src/water2.i

# target to preprocess a source file
src/water2.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water2.cc.i
.PHONY : src/water2.cc.i

src/water2.s: src/water2.cc.s

.PHONY : src/water2.s

# target to generate assembly for a file
src/water2.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/water2.cc.s
.PHONY : src/water2.cc.s

src/wcdLagoCalo.o: src/wcdLagoCalo.cc.o

.PHONY : src/wcdLagoCalo.o

# target to build an object file
src/wcdLagoCalo.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCalo.cc.o
.PHONY : src/wcdLagoCalo.cc.o

src/wcdLagoCalo.i: src/wcdLagoCalo.cc.i

.PHONY : src/wcdLagoCalo.i

# target to preprocess a source file
src/wcdLagoCalo.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCalo.cc.i
.PHONY : src/wcdLagoCalo.cc.i

src/wcdLagoCalo.s: src/wcdLagoCalo.cc.s

.PHONY : src/wcdLagoCalo.s

# target to generate assembly for a file
src/wcdLagoCalo.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCalo.cc.s
.PHONY : src/wcdLagoCalo.cc.s

src/wcdLagoCont.o: src/wcdLagoCont.cc.o

.PHONY : src/wcdLagoCont.o

# target to build an object file
src/wcdLagoCont.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCont.cc.o
.PHONY : src/wcdLagoCont.cc.o

src/wcdLagoCont.i: src/wcdLagoCont.cc.i

.PHONY : src/wcdLagoCont.i

# target to preprocess a source file
src/wcdLagoCont.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCont.cc.i
.PHONY : src/wcdLagoCont.cc.i

src/wcdLagoCont.s: src/wcdLagoCont.cc.s

.PHONY : src/wcdLagoCont.s

# target to generate assembly for a file
src/wcdLagoCont.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdLagoCont.cc.s
.PHONY : src/wcdLagoCont.cc.s

src/wcdpmt.o: src/wcdpmt.cc.o

.PHONY : src/wcdpmt.o

# target to build an object file
src/wcdpmt.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdpmt.cc.o
.PHONY : src/wcdpmt.cc.o

src/wcdpmt.i: src/wcdpmt.cc.i

.PHONY : src/wcdpmt.i

# target to preprocess a source file
src/wcdpmt.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdpmt.cc.i
.PHONY : src/wcdpmt.cc.i

src/wcdpmt.s: src/wcdpmt.cc.s

.PHONY : src/wcdpmt.s

# target to generate assembly for a file
src/wcdpmt.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/wcdpmt.cc.s
.PHONY : src/wcdpmt.cc.s

src/world.o: src/world.cc.o

.PHONY : src/world.o

# target to build an object file
src/world.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/world.cc.o
.PHONY : src/world.cc.o

src/world.i: src/world.cc.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/world.cc.i
.PHONY : src/world.cc.i

src/world.s: src/world.cc.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/world.cc.s
.PHONY : src/world.cc.s

src/worldGround.o: src/worldGround.cc.o

.PHONY : src/worldGround.o

# target to build an object file
src/worldGround.cc.o:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/worldGround.cc.o
.PHONY : src/worldGround.cc.o

src/worldGround.i: src/worldGround.cc.i

.PHONY : src/worldGround.i

# target to preprocess a source file
src/worldGround.cc.i:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/worldGround.cc.i
.PHONY : src/worldGround.cc.i

src/worldGround.s: src/worldGround.cc.s

.PHONY : src/worldGround.s

# target to generate assembly for a file
src/worldGround.cc.s:
	$(MAKE) -f CMakeFiles/lago.dir/build.make CMakeFiles/lago.dir/src/worldGround.cc.s
.PHONY : src/worldGround.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... lago"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... lago.o"
	@echo "... lago.i"
	@echo "... lago.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/CerValHistograms.o"
	@echo "... src/CerValHistograms.i"
	@echo "... src/CerValHistograms.s"
	@echo "... src/CerenkovValidation.o"
	@echo "... src/CerenkovValidation.i"
	@echo "... src/CerenkovValidation.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/ExtraPhysics.o"
	@echo "... src/ExtraPhysics.i"
	@echo "... src/ExtraPhysics.s"
	@echo "... src/OpticalPhysics.o"
	@echo "... src/OpticalPhysics.i"
	@echo "... src/OpticalPhysics.s"
	@echo "... src/PMTHit.o"
	@echo "... src/PMTHit.i"
	@echo "... src/PMTHit.s"
	@echo "... src/PMTSD.o"
	@echo "... src/PMTSD.i"
	@echo "... src/PMTSD.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PhysicsListMessenger.o"
	@echo "... src/PhysicsListMessenger.i"
	@echo "... src/PhysicsListMessenger.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/PrimaryGeneratorMessenger.o"
	@echo "... src/PrimaryGeneratorMessenger.i"
	@echo "... src/PrimaryGeneratorMessenger.s"
	@echo "... src/PrimarySpectrum.o"
	@echo "... src/PrimarySpectrum.i"
	@echo "... src/PrimarySpectrum.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/StepMax.o"
	@echo "... src/StepMax.i"
	@echo "... src/StepMax.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/SteppingVerbose.o"
	@echo "... src/SteppingVerbose.i"
	@echo "... src/SteppingVerbose.s"
	@echo "... src/histosRun.o"
	@echo "... src/histosRun.i"
	@echo "... src/histosRun.s"
	@echo "... src/water.o"
	@echo "... src/water.i"
	@echo "... src/water.s"
	@echo "... src/water2.o"
	@echo "... src/water2.i"
	@echo "... src/water2.s"
	@echo "... src/wcdLagoCalo.o"
	@echo "... src/wcdLagoCalo.i"
	@echo "... src/wcdLagoCalo.s"
	@echo "... src/wcdLagoCont.o"
	@echo "... src/wcdLagoCont.i"
	@echo "... src/wcdLagoCont.s"
	@echo "... src/wcdpmt.o"
	@echo "... src/wcdpmt.i"
	@echo "... src/wcdpmt.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
	@echo "... src/worldGround.o"
	@echo "... src/worldGround.i"
	@echo "... src/worldGround.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

